# Generated by Django 5.1.4 on 2025-01-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=255)),
                ('location_description', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('food_items', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
